export const categories = [
  {
    id: "1",
    name: "Laptops",
    description: "The best laptops you ever seen",
    createdBy: "vasil",
    image: "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e",
    subcategories: [
      {
        id: "1-1",
        name: "Category 1, Subcategory 1",
        description: "First Subcategory of Category 1",
        image: "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e",
        createdBy: "vasil",
        productsCount: 6,
      },
      {
        id: "1-2",
        name: "Category 1, Subcategory 2",
        description: "Second Subcategory of Category 1",
        image: "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e",
        createdBy: "vasil",
        productsCount: 2,
      },
      {
        id: "1-3",
        name: "Category 1, Subcategory 3",
        description: "Third Subcategory of Category 1",
        image: "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e",
        createdBy: "vasil",
        productsCount: 7,
      },
      {
        id: "1-4",
        name: "Category 1, Subcategory 4",
        description: "Forth Subcategory of Category 1",
        image: "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e",
        createdBy: "vasil",
        productsCount: 12,
      },
      {
        id: "1-5",
        name: "Category 1, Subcategory 5",
        description: "Fifth Subcategory of Category 1",
        image: "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e",
        createdBy: "vasil",
        productsCount: 112,
      },
      {
        id: "1-6",
        name: "Category 1, Subcategory 6",
        description: "Sixth Subcategory of Category 1",
        image: "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e",
        createdBy: "vasil",
        productsCount: 131,
      },
      {
        id: "1-7",
        name: "Category 1, Subcategory 7",
        description: "Seventh Subcategory of Category 1",
        image: "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e",
        createdBy: "vasil",
        productsCount: 38,
      },
    ],
  },

  {
    id: "2",
    name: "Games",
    description: "The best games you ever seen",
    createdBy: "vasil",
    image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
    subcategories: [
      {
        id: "2-1",
        name: "Category 2, Subcategory 1",
        description: "First Subcategory of Category 2",
        image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
        createdBy: "valio",
        productsCount: 16,
      },
      {
        id: "2-2",
        name: "Category 2, Subcategory 2",
        description: "Second Subcategory of Category 2",
        image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
        createdBy: "penata",
        productsCount: 4,
      },
      {
        id: "2-3",
        name: "Category 2, Subcategory 3",
        description: "Third Subcategory of Category 2",
        image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
        createdBy: "vasil",
        productsCount: 47,
      },
      {
        id: "2-4",
        name: "Category 2, Subcategory 4",
        description: "Forth Subcategory of Category 2",
        image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
        createdBy: "vasil",
        productsCount: 32,
      },
      {
        id: "2-5",
        name: "Category 2, Subcategory 5",
        description: "Fifth Subcategory of Category 2",
        image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
        createdBy: "vasil",
        productsCount: 54,
      },
      {
        id: "2-6",
        name: "Category 2, Subcategory 6",
        description: "Sixth Subcategory of Category 2",
        image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
        createdBy: "vasil",
        productsCount: 51,
      },
      {
        id: "2-7",
        name: "Category 2, Subcategory 7",
        description: "Seventh Subcategory of Category 2",
        image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
        createdBy: "grisho",
        productsCount: 3,
      },
    ],
  },

  {
    id: "3",
    name: "Home and Garden",
    description: "The best home and garden category you ever seen",
    createdBy: "valcho",
    image: "https://images.unsplash.com/photo-1522770179533-24471fcdba45",
    subcategories: [
      {
        id: "3-1",
        name: "Category 3, Subcategory 1",
        description: "First Subcategory of Category 3",
        image: "https://images.unsplash.com/photo-1522770179533-24471fcdba45",
        createdBy: "valio",
        productsCount: 36,
      },
      {
        id: "3-2",
        name: "Category 3, Subcategory 2",
        description: "Second Subcategory of Category 3",
        image: "https://images.unsplash.com/photo-1522770179533-24471fcdba45",
        createdBy: "penata",
        productsCount: 44,
      },
      {
        id: "3-3",
        name: "Category 3, Subcategory 3",
        description: "Third Subcategory of Category 3",
        image: "https://images.unsplash.com/photo-1522770179533-24471fcdba45",
        createdBy: "vasil",
        productsCount: 17,
      },
      {
        id: "3-4",
        name: "Category 3, Subcategory 4",
        description: "Forth Subcategory of Category 3",
        image: "https://images.unsplash.com/photo-1522770179533-24471fcdba45",
        createdBy: "monkata",
        productsCount: 22,
      },
      {
        id: "3-5",
        name: "Category 3, Subcategory 5",
        description: "Fifth Subcategory of Category 3",
        image: "https://images.unsplash.com/photo-1522770179533-24471fcdba45",
        createdBy: "vasil",
        productsCount: 25,
      },
      {
        id: "3-6",
        name: "Category 2, Subcategory 6",
        description: "Sixth Subcategory of Category 3",
        image: "https://images.unsplash.com/photo-1522770179533-24471fcdba45",
        createdBy: "gencho",
        productsCount: 21,
      },
      {
        id: "3-7",
        name: "Category 3, Subcategory 7",
        description: "Seventh Subcategory of Category 3",
        image: "https://images.unsplash.com/photo-1522770179533-24471fcdba45",
        createdBy: "vasil",
        productsCount: 43,
      },
    ],
  },

  {
    id: "4",
    name: "Kids and Toys",
    description: "The best Kids and Toys category you ever seen",
    createdBy: "bintaka",
    image: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
    subcategories: [
      {
        id: "4-1",
        name: "Category 4, Subcategory 1",
        description: "First Subcategory of Category 4",
        image: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
        createdBy: "tombata",
        productsCount: 6,
      },
      {
        id: "4-2",
        name: "Category 4, Subcategory 2",
        description: "Second Subcategory of Category 4",
        image: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
        createdBy: "penata",
        productsCount: 14,
      },
      {
        id: "4-3",
        name: "Category 4, Subcategory 3",
        description: "Third Subcategory of Category 4",
        image: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
        createdBy: "vasil",
        productsCount: 22,
      },
      {
        id: "4-4",
        name: "Category 4, Subcategory 4",
        description: "Forth Subcategory of Category 4",
        image: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
        createdBy: "monkata",
        productsCount: 54,
      },
      {
        id: "4-5",
        name: "Category 4, Subcategory 5",
        description: "Fifth Subcategory of Category 4",
        image: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
        createdBy: "vasil",
        productsCount: 31,
      },
      {
        id: "4-6",
        name: "Category 4, Subcategory 6",
        description: "Sixth Subcategory of Category 4",
        image: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
        createdBy: "gencho",
        productsCount: 43,
      },
      {
        id: "4-7",
        name: "Category 4, Subcategory 7",
        description: "Seventh Subcategory of Category 4",
        image: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
        createdBy: "vasil",
        productsCount: 50,
      },
    ],
  },

  {
    id: "5",
    name: "Fashion",
    description: "The best Fashion category you ever seen",
    createdBy: "bintaka",
    image: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
    subcategories: [
      {
        id: "5-1",
        name: "Category 5, Subcategory 1",
        description: "First Subcategory of Category 5",
        image: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
        createdBy: "tombata",
        productsCount: 16,
      },
      {
        id: "5-2",
        name: "Category 5, Subcategory 2",
        description: "Second Subcategory of Category 5",
        image: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
        createdBy: "penata",
        productsCount: 64,
      },
      {
        id: "5-3",
        name: "Category 5, Subcategory 3",
        description: "Third Subcategory of Category 5",
        image: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
        createdBy: "vasil",
        productsCount: 82,
      },
      {
        id: "5-4",
        name: "Category 5, Subcategory 5",
        description: "Forth Subcategory of Category 5",
        image: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
        createdBy: "monkata",
        productsCount: 44,
      },
      {
        id: "5-5",
        name: "Category 5, Subcategory 5",
        description: "Fifth Subcategory of Category 5",
        image: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
        createdBy: "vasil",
        productsCount: 34,
      },
      {
        id: "5-6",
        name: "Category 5, Subcategory 6",
        description: "Sixth Subcategory of Category 5",
        image: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
        createdBy: "gencho",
        productsCount: 16,
      },
      {
        id: "5-7",
        name: "Category 5, Subcategory 7",
        description: "Seventh Subcategory of Category 5",
        image: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
        createdBy: "vasil",
        productsCount: 30,
      },
    ],
  },
];
